"""phase3 acquired skills, snapshots, prefs

Revision ID: 2a3d01bcedc1
Revises: 9f302f40dd08
Create Date: 2026-07-23 14:28:29.910022

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a3d01bcedc1'
down_revision: Union[str, Sequence[str], None] = '9f302f40dd08'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acquired_skills',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('skill_id', sa.String(), nullable=False),
    sa.Column('proficiency', sa.String(), nullable=False),
    sa.Column('source_activity_id', sa.String(), nullable=True),
    sa.Column('acquired_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acquired_skills_id'), 'acquired_skills', ['id'], unique=False)
    op.create_table('progress_snapshots',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.Column('coverage_pct', sa.Integer(), nullable=False),
    sa.Column('acquired_count', sa.Integer(), nullable=False),
    sa.Column('taken_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_progress_snapshots_id'), 'progress_snapshots', ['id'], unique=False)
    op.create_table('user_prefs',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('weekly_goal_hours', sa.Integer(), nullable=False),
    sa.Column('digest_opt_in', sa.Integer(), nullable=False),
    sa.Column('timezone', sa.String(), nullable=True),
    sa.Column('last_digest_at', sa.DateTime(), nullable=True),
    sa.Column('streak_weeks', sa.Integer(), nullable=False),
    sa.Column('streak_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_prefs')
    op.drop_index(op.f('ix_progress_snapshots_id'), table_name='progress_snapshots')
    op.drop_table('progress_snapshots')
    op.drop_index(op.f('ix_acquired_skills_id'), table_name='acquired_skills')
    op.drop_table('acquired_skills')
    # ### end Alembic commands ###
