"""baseline schema

Revision ID: d1d45cb531b6
Revises: 
Create Date: 2026-07-22 17:12:24.127171

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1d45cb531b6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema.

    Idempotent baseline: on the EXISTING production DB these three tables already
    exist (they were created by create_all before Alembic was introduced), and
    there is no alembic_version row yet. Guarding each create_table with a
    has_table() check lets `alembic upgrade head` run safely on both a fresh DB
    (creates everything) and the live DB (skips existing tables, records the
    version) — no manual `alembic stamp` step required.
    """
    insp = sa.inspect(op.get_bind())
    existing = set(insp.get_table_names())

    if 'users' not in existing:
        op.create_table('users',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('email', sa.String(), nullable=False),
        sa.Column('password_hash', sa.String(), nullable=False),
        sa.Column('password_salt', sa.String(), nullable=False),
        sa.Column('iterations', sa.Integer(), nullable=False),
        sa.Column('persona', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
        op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    if 'analyses' not in existing:
        op.create_table('analyses',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('profile_json', sa.JSON(), nullable=False),
        sa.Column('forecasts_json', sa.JSON(), nullable=False),
        sa.Column('pathways_json', sa.JSON(), nullable=False),
        sa.Column('courses_json', sa.JSON(), nullable=False),
        sa.Column('trace_json', sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    if 'learning_activities' not in existing:
        op.create_table('learning_activities',
        sa.Column('id', sa.String(), nullable=False),
        sa.Column('user_id', sa.String(), nullable=False),
        sa.Column('course_id', sa.String(), nullable=True),
        sa.Column('title', sa.String(), nullable=False),
        sa.Column('provider', sa.String(), nullable=True),
        sa.Column('url', sa.String(), nullable=True),
        sa.Column('skill_ids', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_learning_activities_id'), 'learning_activities', ['id'], unique=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_learning_activities_id'), table_name='learning_activities')
    op.drop_table('learning_activities')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_table('analyses')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
